services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8101
      - TORRENTING_PORT=6881
    volumes:
      - ./data/qbittorrent/config:/config
      - /mnt/nfs/media:/mnt/media
    ports:
      - 8101:8101
      - 52866-52867:52866-52867
      - 52866-52867:52866-52867/udp
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/sabnzbd/config:/config
      - /mnt/nfs/media:/mnt/media
    ports:
      - 8102:8080
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/radarr/config:/config
      - /mnt/nfs/media:/mnt/media
    ports:
      - 8201:7878
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - sabnzbd
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/sonarr/config:/config
      - /mnt/nfs/media:/mnt/media
    ports:
      - 8202:8989
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - sabnzbd
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/lidarr/config:/config
      - /mnt/nfs/media:/mnt/media
    ports:
      - 8203:8686
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - sabnzbd
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/readarr/config:/config
      - /mnt/nfs/media:/mnt/media
    ports:
      - 8204:8787
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - sabnzbd

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/prowlarr/config:/config
    ports:
      - 8301:9696
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
      - lidarr
      - readarr
  ombi:
    image: lscr.io/linuxserver/ombi:4.43.14-development
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- BASE_URL=/ombi #optional
    volumes:
      - ./data/ombi/config:/config
    ports:
      - 8302:3579
    restart: unless-stopped
    depends_on:
      - prowlarr
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/homarr/configs:/app/data/configs
      - ./data/homarr/icons:/app/public/icons
      - ./data/homarr/data:/data
    ports:
      - '8303:7575'
    restart: unless-stopped
    depends_on:
      - prowlarr
